# Generated by Django 6.0.4 on 2026-04-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(blank=True, verbose_name='Comment (EN)'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(default='', verbose_name='Комментарий (RU)'),
            preserve_default=False,
        ),
    ]
