# Generated by Django 6.0.4 on 2026-04-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name_ru'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название (RU)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name (EN)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название (RU)'),
            preserve_default=False,
        ),
    ]
